Userの評価のカウントの実装
yossy/freemarket_sample_41a pull request #109
Opened 2019-01-22 11:10 UTC by ALL5B

# What
商品詳細ページ、マイページのプロフィールに評価の合計値を記述
# Why
ユーザーの信頼性の向上のため
評価の総合計
評価ランク別の数値を表示

2019-01-22 11:24 UTC, ReoKuriyama commented on app/controllers/application_controller.rb
> +  def good_rate_count(user)
userモデルに定義しましょう

2019-01-22 12:04 UTC, ALL5B commented on app/controllers/application_controller.rb
> +  def good_rate_count(user)
お伺いしたいのですが、モデルで定義したメソッドはコントローラーで引き出すことが出来るのでしょうか？

2019-01-22 12:09 UTC, ReoKuriyama commented on app/controllers/application_controller.rb
> +  def good_rate_count(user)
モデルで定義するということはUserモデルに対してメソッドを生やすことになるのでuserインスタンスに対して全ての場所で呼び出すことができるようになります。
よってコントローラーでも呼び出せます。

2019-01-22 12:23 UTC, ALL5B commented on app/controllers/application_controller.rb
> +  def good_rate_count(user)
ありがとうございます！修正します！！

2019-01-22 12:28 UTC, ghost requested changes

2019-01-22 12:28 UTC, ghost commented on app/controllers/application_controller.rb
> +
こういった不要な変更は無くしましょう

2019-01-22 12:28 UTC, ghost commented on app/controllers/products_controller.rb
> +  require "user.rb"
これがなくても動くと思うのですが、これがないと動かないですか？

2019-01-23 11:25 UTC, ALL5B commented on app/controllers/application_controller.rb
> +
修正しました！

2019-01-23 11:25 UTC, ALL5B commented on app/controllers/products_controller.rb
> +  require "user.rb"
修正しました！

2019-01-23 11:33 UTC, kuroko918 commented
LGTMです！

2019-01-23 11:37 UTC, merged