商品出品ページのjavascriptの実装
yossy/freemarket_sample_41a pull request #88
Opened 2019-01-18 11:21 UTC by Taiki0806

# WHAT
出品ページのjavascriptの実装。
・price.jsでは価格のカンマ区切り、
手数料の計算を実装。
・product_preview.jsでは、
ファイル選択時に動的に
ファイルの読み込み、
プレビューの表示を実装。
ファイル選択エリアはプレビューの数に応じてwidthを変換しています。
・selectbox.jsでは、
独自属性にidを
セレクトボックスに与え、
セレクトボックスのvalueを取得し、
一致すれば表示するというように実装。
・ビューとsassはjsに合うように
微修正。

# WHY
利便性を高めユーザーの出品への
ハードルを下げるため。

2019-01-18 11:25 UTC, yossy commented
すみません！
今からjsの実装箇所のgyazoを貼ります！

2019-01-18 11:26 UTC, ShuheiTsuji commented on app/assets/javascripts/product_preview.js
> +    var fileA = $(".have-item1").find(".file").val().length;
このような同じ処理はまとめて書けるとさらに良いコードになりますね！

2019-01-18 11:26 UTC, ShuheiTsuji commented on app/assets/javascripts/product_preview.js
> +  $("#product_product_images_attributes_1_image").parent().hide();
このような同じ処理はまとめて書けるとさらに良いコードになりますね！

2019-01-18 11:26 UTC, ShuheiTsuji commented on app/assets/javascripts/product_preview.js
> +    if(fileA == 0){
こういったところも同じなので工夫すれば行数は減らせます！

2019-01-18 11:26 UTC, ShuheiTsuji commented on app/assets/javascripts/product_preview.js
> +  // 商品画像２
ここもですね！

2019-01-18 11:26 UTC, ShuheiTsuji commented on app/controllers/products_controller.rb
> +    @categoryroot = Category.find(1).siblings
この処理は、関数名つけて new と edit の共通のメソッドとして定義してあげる方が行数少なくて良いかもしれないですね。
ただ、このままでも全然問題ないです。
そういった書き方もあります！

2019-01-18 11:29 UTC, yossy commented
プレビュー表示
[![Image from Gyazo](https://i.gyazo.com/db911bce68868c01702437fca52ed592.gif)](https://gyazo.com/db911bce68868c01702437fca52ed592)

2019-01-18 11:32 UTC, Taiki0806 commented
カテゴリーボックス
[![Image from Gyazo](https://i.gyazo.com/230f63eaecec2443bbf509cc14558cb3.gif)](https://gyazo.com/230f63eaecec2443bbf509cc14558cb3)

2019-01-18 11:33 UTC, Taiki0806 commented
価格
[![Image from Gyazo](https://i.gyazo.com/9856bc33ef00760cb7001fa8dcd56a3a.gif)](https://gyazo.com/9856bc33ef00760cb7001fa8dcd56a3a)

2019-01-19 09:42 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +    var fileA = $(".have-item1").find(".file").val().length;
each文で回す形で修正しました。

2019-01-19 09:43 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +  $("#product_product_images_attributes_1_image").parent().hide();
each文で回して番号で管理する形に修正しました。

2019-01-19 09:44 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +    if(fileA == 0){
each文で管理する形に修正しました。

2019-01-19 09:45 UTC, Taiki0806 commented on app/controllers/products_controller.rb
> +    @categoryroot = Category.find(1).siblings
わかりました！
ありがとうございます！

2019-01-19 09:47 UTC, Taiki0806 commented
product_preview.jsのリファクタリングと、
selectbox.jsの修正、
それに伴うnew.html.hamlの修正を行いました。
ご確認よろしくお願いいたします！

2019-01-19 09:49 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +  // 商品画像２
上記と同じくeach文で記述する形に編集しました。

2019-01-19 11:04 UTC, yuki-uchida requested changes

2019-01-19 11:04 UTC, yuki-uchida commented on app/assets/javascripts/price.js
> +  function separate(num){
separateでは何をどうするものかわからないので、もっと具体的に書いて大丈夫です

2019-01-19 11:04 UTC, yuki-uchida commented on app/assets/javascripts/product_preview.js
> +  function widthEdit() {
editImgWidthなどで良いでしょう

2019-01-19 11:04 UTC, yuki-uchida commented on app/assets/javascripts/product_preview.js
> +  function imgCount() {
countPreviewImagesなどで良いでしょう

2019-01-19 11:04 UTC, yuki-uchida commented on app/assets/javascripts/product_preview.js
> +  function inputCheck(){
ShowNoInputAreaなどはいかがでしょうか

2019-01-19 11:04 UTC, yuki-uchida commented on app/assets/javascripts/product_preview.js
> +  function inputCheckA(){
こちらもですね

2019-01-19 11:11 UTC, Taiki0806 commented on app/assets/javascripts/price.js
> +  function separate(num){
ご指摘ありがとうございます！
addCommaPriceに関数名を変更しました！

2019-01-19 11:21 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +  function inputCheck(){
値を持たない最後の画像選択エリアを見えるようにする関数のため、
ShowNoInputAreaLastに変更いたしました！

2019-01-19 11:21 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +  function imgCount() {
countPreviewImagesに変更いたしました！

2019-01-19 11:21 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +  function widthEdit() {
editImgWidthに変更いたしました！

2019-01-19 11:21 UTC, Taiki0806 commented on app/assets/javascripts/product_preview.js
> +  function inputCheckA(){
ShowNoInputAreaに変更いたしました！

2019-01-19 11:24 UTC, yossy commented
関数名をわかりやすく命名するのは自分とチームのために
とても大事なことであると再認識いたしました。
ありがとうございます。
ご確認よろしくお願いいたします。

2019-01-19 11:26 UTC, yuki-uchida approved these changes
LGTMです！

2019-01-19 11:27 UTC, yossy commented
ありがとうございます！

2019-01-19 11:27 UTC, merged